spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MgBronya233/toBeJavaer # 配置git仓库的地址
          search-paths: framework/SpringCloud/config-repo/ # git仓库地址下的相对地址，可以配置多个，用,分割。
    bus:
      enabled: true
      trace:
        enabled: true
server:
  port: 10000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/